import esbuild from "esbuild";
import process from "node:process";
import fs from "node:fs";
import path from "node:path";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/rokokol/obsidian-fsrs-vocabulary
*/`;

const production = process.argv[2] === "production";

/** Files copied to the vault plugin dir after a successful build. */
const artifacts = ["main.js", "manifest.json", "styles.css"];

/**
 * Copy build artifacts into the Obsidian vault plugin folder, if configured.
 * Path comes from OBSIDIAN_PLUGIN_DIR (a local .env or the shell env) so the
 * public repo never hardcodes a machine-specific vault path.
 */
function copyToVault() {
  const target = process.env.OBSIDIAN_PLUGIN_DIR;
  if (!target) return;
  fs.mkdirSync(target, { recursive: true });
  for (const file of artifacts) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(target, file));
    }
  }
  console.log(`[fsrs-vocabulary] copied artifacts -> ${target}`);
}

const copyPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) copyToVault();
    });
  },
};

/**
 * `import source from "inline-worker:./worker"` bundles that module on its own and
 * hands back the bundle as text, which the plugin turns into a Web Worker through a
 * blob URL. The plugin ships as main.js alone, so a worker cannot be a file of its
 * own; and a WebAssembly module the worker imports is inlined as bytes for the same
 * reason.
 */
const inlineWorker = {
  name: "inline-worker",
  setup(build) {
    build.onResolve({ filter: /^inline-worker:/ }, (args) => ({
      path: path.resolve(args.resolveDir, args.path.slice("inline-worker:".length)),
      namespace: "inline-worker",
    }));
    build.onLoad({ filter: /.*/, namespace: "inline-worker" }, async (args) => {
      const result = await esbuild.build({
        entryPoints: [args.path],
        resolveExtensions: [".ts", ".js"],
        bundle: true,
        write: false,
        format: "iife",
        target: "es2022",
        minify: production,
        loader: { ".wasm": "binary" },
        // fsrs-browser locates its own files from import.meta.url, on paths the
        // worker never takes: it is given its module as bytes and starts no threads.
        define: { "import.meta.url": '"about:blank"' },
        logLevel: "warning",
        metafile: true,
      });
      return {
        contents: result.outputFiles[0].text,
        loader: "text",
        watchFiles: Object.keys(result.metafile.inputs).map((file) => path.resolve(file)),
      };
    });
  },
};

// Load OBSIDIAN_PLUGIN_DIR from a local .env if present (dev convenience).
const envFile = path.resolve(".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split("\n")) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (match && match[1] && !process.env[match[1]]) {
      process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  plugins: [inlineWorker, copyPlugin],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
